spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.139:3306/cloudplatformtest
    username: root
    password: Admin123!
    type: com.zaxxer.hikari.HikariDataSource
    #连接池配置
    hikari:
      minimum-idle: 5
      idle-timeout: 6000000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MYHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #上传设置
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
      enabled: false
      location: D:/home/cloud/file/cache




#session过期时间
server:
  servlet:
    session:
      timeout: 18000
  port: 8080

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



#上传文件映射地址#
contextPath: D:/home/cloud/file/
#签章测试服务器文件地址
iWebOffice: D:/work/apache-tomcat-9.0.21/webapps/iWebPDF2018/
#rvt文件保存路径
rvtPath: D:/home/cloud/file/


#外部接口参数
YunFileUrl: http://39.100.51.224:8020/ZhiJunYun/
JWUrl: http://jsgl.zfcxjw.cq.gov.cn:7003/CqBim/
YunFileTocken: e0ec790c53f7
ZZJUrl: http://jsgl.zfcxjw.cq.gov.cn:7003/CqBim/

#跨域设置
allowedOriginsIP: http://192.168.110.50:80



token:
  expire:
    #24小时在线时间
    seconds: 86400000
  jwtSecret: (ZHI:)_$^11244^%$_(CHEN:)_@@++--(YUN:)_++++_.sds_(KE:)

